spring:
  profiles:
    active: dev # can give multiple profiles at same time with comma

logging:
  level:
    com:
      meet:
        myFirstProject: DEBUG
#   root: ERROR // this is to set root level logs
#   You can set levels of logs to different classes and packages as per needs

# Levels of logging
#   -Trace
#   -Debug
#   -Info
#   -Warn
#   -Error

# You can also change this by command line arguments with the jar when in production