#spring.application.name=myFirstProject
#
#spring.data.mongodb.uri=mongodb+srv://meet57mp:Admin%40123@journal.9w7qd.mongodb.net/?retryWrites=true&w=majority&appName=Journal
#spring.data.mongodb.database=journaldb
#spring.data.mongodb.auto-index-creation=true
#logging.level.org.springframework.security=DEBUG